// USER
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_USER = "LOADING_USER";
export const SET_PROFILE = "SET_PROFILE";
export const FOLLOW_USER = "FOLLOW_USER";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const LOADING_SUGGESTION = "LOADING_SUGGESTION";
export const SET_FOLLOW_SUGGESTION = "SET_FOLLOW_SUGGESTION";
export const LOADING_TREND = "LOADING_TREND";
export const SET_TRENDS = "SET_TRENDS";
export const SEARCH_USER_RESULTS = "SEARCH_USER_RESULTS";
export const SEARCH_TREND_RESULTS = "SEARCH_TREND_RESULTS";

// UI
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_FLASH_MSG = "SET_FLASH_MSG";

// DATA
export const SET_TWEETS = "SET_TWEETS  ";
export const LOADING_DATA = "LOADING_DATA";
export const LIKE_TWEET = "LIKE_TWEET";
export const UNLIKE_TWEET = "UNLIKE_TWEET";
export const DELETE_TWEET = "DELETE_TWEET";
export const ADD_TWEET = "ADD_TWEET";
export const SET_TWEET = "SET_TWEET";
export const COMMENT_TWEET = "COMMENT_TWEET";
export const LOADING_COMMENT = "LOADING_COMMENT";
export const STOP_LOADING_COMMENT = "STOP_LOADING_COMMENT";
export const SET_LISTS = "SET_LISTS";
export const SET_LIST_DETAILS = "SET_LIST_DETAILS";
export const FOLLOW_LIST = "FOLLOW_LIST";
export const SET_BOOKMARKS = "SET_BOOKMARKS";
export const GET_BOOKMARKS = "GET_BOOKMARKS";

//Chat
export const LOADING_CONVERSATION = "LOADING_CONVERSATION";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const GET_CONVERSATION = "GET_CONVERSATION";
export const SEND_MESSAGE = "SEND_MESSAGE";
